# cspell: ignore nojekyll
name: documentation
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [closed]
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          sudo apt update && sudo apt install -y doxygen && \
          python -m venv .venv-mkdocs && \
          . .venv-mkdocs/bin/activate && \
          pip install -r docs/requirements.txt Jinja2 ruamel.yaml && \
          pip install git+https://github.com/JakubAndrysek/mkdoxy && \
          deactivate && \
          python -m venv .venv-zensical && \
          . .venv-zensical/bin/activate && \
          pip install zensical==0.0.15
      - run: PATH="$PWD/.venv-mkdocs/bin:$PATH" .venv-mkdocs/bin/python scripts/build_zensical_docs_source.py
      - run: .venv-zensical/bin/zensical build -f .zensical/mkdocs.yml -c
      - run: touch .zensical/site/.nojekyll
      - run: |
          chmod -c -R +rX ".zensical/site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .zensical/site
      - uses: actions/deploy-pages@v4
